# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45cab27e0cf2e60142cd31ccadb3ef34b9566dd4fc2cfa2f5b509181448b8b40da58eb1ad4795191597d589839ed157adefab849b0c7bb0ebc9aa5296639e430

test:
  secret_key_base: effbbdc05704e0ebc9efc1102a70286340bf0a5e44cfbcaa28e910cd31180fdec2e32162ef33c9acf0f4b9d8c196e2610866df06d05f4833c2fd59bcf1e5ebab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
